### ISSUE TITLE
Oracle - error when using quotes around cdmFieldName

### ISSUE THREAD

**Issue by alondhe** [OHDSI/DataQualityDashboard#100]
Raised by @Andreyyiv -- in trying to use quotes around the cdmFieldName value for the query field_cdm_field.sql (to protect against the usage of the field name offset, which is a SQL keyword in PG), we have an Oracle issue. Oracle can only use quotes around a field name in order to assert case sensitivity. 

So, Oracle will fail on using something like select "condition_concept_id", but would succeed on select condition_concept_id. We could try using select "CONDITION_CONCEPT_ID", which assumes the user has not explicitly selected a case sensitive field name in their CDM.

**Comment by dmitryilyn** [comment]
Our partners also faced with similar issue in Oracle.
For example, this query fails in Oracle because of using double quotes in COUNT("care_site_id"):
`SELECT num_violated_rows, CASE WHEN denominator.num_rows = 0 THEN 0 ELSE 1.0*num_violated_rows/denominator.num_rows END AS pct_violated_rows
FROM (SELECT num_violated_rows FROM (SELECT  CASE when  COUNT("care_site_id") = 0 then 0
      else 0
     END as num_violated_rows
    FROM omop.VISIT_OCCURRENCE
    GROUP BY 1) violated_rows
) violated_row_count,
(SELECT 1 as num_rows
FROM DUAL) denominator
;`

**Comment by alondhe** [comment]
@dmitryilyn -- the develop branch, being reviewed, should address this.

If you'd like to try it:

restart R
`remove.packages("DataQualityDashboard")`
`devtools::install_github("OHDSI/DataQualityDashboard", ref = "develop")`

**Comment by dmitryilyn** [comment]
@alondhe Thank you!
