### ISSUE TITLE
Test Marked as Passed But Below Completeness Threshold

### ISSUE THREAD

**Issue by CartWill** [OHDSI/DataQualityDashboard#106]
For some of the tests it appears that the thresholds are not being applied correctly.  We have a test, test id 2, where the threshold is 95% and the PCT_VIOLATED_ROWS is below that.  The test is marked as passed.  Shouldn't it be marked as failed if the PCT_VIOLATED_ROWS is less than the threshold if measuring completeness?

**Comment by alondhe** [comment]
Hi @CartWill -- can you give the check name that this is happening for? The check Ids don't mean anything (right now, we're working on assigning permanent check ids).

**Comment by CartWill** [comment]
@alondhe The check name is 

> measurePersonCompleteness 

and the description is 

> The number and percent of persons in the CDM that do not have at least one record in the   VISIT_OCCURRENCE table

The threshold is 95% and our PCT_VIOLATED_ROWS is less than the threshold but it's marked as passed.

**Comment by alondhe** [comment]
@CartWill -- yeah, that's odd. The logic is below; if that is true, it gets a FAIL. 

`checkResults[i,]$PCT_VIOLATED_ROWS * 100 > thresholdValue `

Can you ensure you have the latest version, and re-run it, but let's just run measurePersonCompleteness. Use the parameters below in the executeDqChecks function call.

`checkLevels = c("TABLE"), checkNames = c("measurePersonCompleteness")`

Do you still see FAILs for checks that have a PCT_VIOLATED_ROWS value < the threshold?

**Comment by CartWill** [comment]
We are using the version from the develop branch because that seems to the be the only one that runs most correctly for Google BigQuery right now.  I re-ran it with the parameters you specified and it does seem where the PCT_VIOLATED_ROWS is less than the threshold they are not flagged.  

So if I read the logic correctly there, something is only considered a fail if the PCT_VIOLATED_ROWS is greater than the threshold.  Shouldn't the comparison depend on the type test or are these tests trying to check something like the records matching up more than 95% would be too good to be true?

**Comment by alondhe** [comment]
It does depend on the test type, but for this particular test (measurePersonCompleteness), the fail status is given if the percentage of violated rows is greater than the allowable threshold. 

The develop branch is a good version to run, we're finishing review of it before merging into master. There's fixes for bigquery and oracle, but nothing is changed with the threshold evaluation.

So if running just this 1 check yields the expected result (pct_violated_rows < threshold = SUCCESS), can you try re-running it fully?

**Comment by clairblacketer** [comment]
For all checks if the percent rows that fail falls above the given threshold then the check fails. It would be confusing to change the meaning of the threshold from check to check so this is the logic across the board. @CartWill what you can do, however, is change the threshold based on your needs/understanding of the data. The ones in the csv files are suggestions and meant to be changed site to site and database to database.

**Comment by don-torok** [comment]
I've been looking at field level check measureValueCompleteness which is a simple check of how many row are NULL over total number of rows.  But what I think is confusing people is that measureValueCompletenessThreshold is the percent of **failed** rows that you are willing to accept.  For example, location.address_2 has measureValueCompleteness = 'Yes' and measureValueCompletenessThreshold = 100.  Now in the data every row is NULL so the test result is number of violating rows = 5112 and total number of rows = 5112 and %_violating_rows = 5112/5112 = 1.  Then the test for failure is %_violating_row * 100 > Threshold or (1 * 100) > 100.  100% of the rows failed, but that is NOT greater than the threshold, the test **Passed**.  Intuitively and by the example settings you think the threshold is the number of non-violating rows/total, but that is incorrect.   You either have to make it clear that the threshold is the % of failed rows you are willing to accept, or change the test for failure to be (1 **minus** violating_row/total_row) * 100 > threshold so that the threshold is the minimum % of positives you are willing to accept.
