### ISSUE TITLE
Specify different vocabulary schema

### ISSUE THREAD

**Issue by clairblacketer** [OHDSI/DataQualityDashboard#113]
Currently the DQD assumes that the vocabulary will be embedded in the CDM. While that is best practice, we should also add a parameter that allows the user to specify a different vocabulary schema if necessary.

**Comment by alondhe** [comment]
Not disagreeing, but I think the original argument against this was that the CDM specification requires the vocab tables be in the CDM schema. That way the CDM source is a complete picture of the build. 

However, Atlas does allow for it to exist elsewhere when setting up CDM sources, and we have this in Achilles as well. It is nice to have this flexibility, but since DQD is often used as a first or second step post-build I wonder if we should be pushing sites towards the specification more.

**Comment by clairblacketer** [comment]
Fair, but in my specific case I have a small dataset on a small server where I couldn’t house more than one version of the vocabulary due to size. I then had to make changes to the dqd just to run all the checks. I would prefer the vocab to be part of the CDM but it’s not always possible
