### ISSUE TITLE
information outside of obs period

### ISSUE THREAD

**Issue by clairblacketer** [OHDSI/DataQualityDashboard#143]
https://forums.ohdsi.org/t/patient-medical-history-events-outside-observation-period/6945/5

**Comment by fdefalco** [comment]
After discussion we believe that the volume of data that falls outside of an observation period is important to characterize, however because the CDM specification and guidelines allow for data to occur outside of an observation period, it is not inherently a data quality issue for this to occur.  Our plan is to add a new characterization to Achilles that allows the exploration of the volume of data occurring outside of an observation period.
