### ISSUE TITLE
Read Timed out error when the value of timeout is large enough

### ISSUE THREAD

**Issue by jahoon1998** [OHDSI/DataQualityDashboard#303]
I have set the time out value in the connection JDBC URL 2000000 seconds, but still experiencing the SQL read timed out issue. 
Has anyone had a similar issue?

![dqd github issue](https://user-images.githubusercontent.com/35817244/161107668-e071262c-4cd2-4b8f-a14c-349173549aa1.PNG)
![dqd github issue 1](https://user-images.githubusercontent.com/35817244/161107639-598a1da7-3906-4a31-b72f-8b6ccb0ec5e5.PNG)

Machine type: CentOS 7 
SIMBA JDBC Driver Version: 1.2.22.1026.
CDM version: 5.3.1

Thank you.
Jahoon

**Comment by jahoon1998** [comment]
@clairblacketer @fdefalco Please let me know if you find anything about the issue.

**Comment by fdefalco** [comment]
Could you share the content of the error report file that is listed in the error message? 

Also, are you able to run the query listed in the details section outside of the DQD process.  This appears to be database timeout due to the duration of the query that is running, however we haven't seen particular performance issues with this query in the past.

**Comment by katy-sadowski** [comment]
@jahoon1998 i'll close this out for now, but please do re-open if you are still experiencing this issue and need any support.
