### ISSUE TITLE
special characters in metadata

### ISSUE THREAD

**Issue by alondhe** [OHDSI/DataQualityDashboard#33]
When pulling the CDM source metadata, special characters encoded in latin1 are brought into the JSON file. When calling viewDqDashboard, the jsonlite call to read the JSON fails due to these characters. 

Need to re-encode to UTF-8?

**Comment by clairblacketer** [comment]
I think Frank had this problem last week too

**Comment by alondhe** [comment]
I've worked around it by using the iconv() function, converting from Latin1 to utf8. But, that doesn't display well in the GUI

**Comment by clairblacketer** [comment]
@fdefalco should we try to fix this?

**Comment by clairblacketer** [comment]
@AnthonyMolinaro please implement the fix we use to make sure the encoding is UTF-8

**Comment by clairblacketer** [comment]
closed with PR #292

**Comment by MaximMoinat** [comment]
This fix has been reverted per commit 4a34a47, to comply with HADES 'avoid hidden effects' rule.
After talking with Ajit, agreed to remove the global encoding options entirely as the issue could not be reproduced. If the issue reoccurs, then it should be properly fixed by explicitly checking the encoding. See the following CohortDiagnostic functions: 
[checkInputFileEncoding](https://github.com/OHDSI/CohortDiagnostics/blob/5f4d80e9f4210ffaf2ac7d4ab2b26102e4987c58/R/Private.R#L94), [DataSourceInformation.R](https://github.com/OHDSI/CohortDiagnostics/blob/5f4d80e9f4210ffaf2ac7d4ab2b26102e4987c58/R/DataSourceInformation.R)
