### ISSUE TITLE
Efficient SQL-only option to insert all results into dqdashboard_results table

### ISSUE THREAD

**Issue by TMSWhite** [OHDSI/DataQualityDashboard#333]
As-is, the sqlOnly option has 4 main limitations:

- It requires connectivity to a live OMOP instance
- It does not include the metadata about the test being run
- It does not insert the results into the dqdashboard_results table
- It is inefficient, running all ~3000 tests serially rather than in parallel

[Pull request # 301](https://github.com/OHDSI/DataQualityDashboard/pull/301) solves all of these issues.  Users can specify the # of tests to run in parallel, and they are composed into a CTE before the full set of them are inserted into the output table.  In tests on Spark with 4 years of data and 3 million patients, performance improved from 16 hours to run all tests serially to about an hour to run them on a Spark cluster (e.g. DataBricks or HDInsight) and insert all results into dqdashboard_results.

**Comment by katy-sadowski** [comment]
This has officially been released!  Thanks so much @TomWhite-MedStar for contributing this code!!!  I enjoyed the collaboration and am excited to see how this new addition will benefit our community.

It'd be great to have you attend a Data Quality workgroup meeting to present the feature - we are actually meeting this Thursday 5/25 at 9:30am eastern time in case that works for you.  Otherwise we can choose another one in the future.  Several members already expressed interest in testing out the feature; I'm looking forward to getting their input & performance benchmarks :)
