### ISSUE TITLE
Vocab schema

### ISSUE THREAD

**Issue by galachad** [OHDSI/DataQualityDashboard#347]
vocabDatabaseSchema is not fully support the field check, it's throwing error on some check: e.g. IS_FOREIGN_KEY, FIELD LEVEL and FIELD_IS_NOT_NULLABLE.

**Comment by clairblacketer** [comment]
Hi @galachad can you elaborate here? vocabDatabaseSchema should be the schema where your vocabulary is held as the OMOP vocabulary is used for some DQD checks.

**Comment by galachad** [comment]
We keep all the vocabularies in separate schema ([defined as VOCAB schema in CDM](https://github.com/OHDSI/CommonDataModel/blob/main/inst/csv/OMOP_CDMv5.4_Table_Level.csv)). In DQD it's defines as vocabDatabaseSchema. In case of running some of the field check the `vocabDatabaseSchema` are not supported for checking fields.

Example:
```
Error:
java.sql.SQLException: [Amazon](500310) Invalid operation: relation "cdm.drug_strength" does not exist;
```

The `drug_strenght` should be taken from the vocab schema.


The vocabulary table are not only CONCEPT and DOMAIN. https://github.com/OHDSI/DataQualityDashboard/blob/main/inst/sql/sql_server/is_foreign_key.sql

**Comment by clairblacketer** [comment]
@galachad this makes sense. Essentially the DQD is assuming the vocabulary is in the same schema as the data, which is incorrect. I will add this as a bug to be fixed in v2.0

**Comment by katy-sadowski** [comment]
Good call-out @tlecarrour-ee .  We should use the `cohortDatabaseSchema` here instead of `cdmDatabaseSchema`.  I'll address this together with the vocab schema issue.  Thanks!

**Comment by katy-sadowski** [comment]
Fixed in v2.2.0 release. Please comment here if you're still experiencing issues with the latest DQD version!

**Comment by tlecarrour-ee** [comment]
Thanks @katy-sadowski, I will test it ASAP.

**Comment by RomainTching** [comment]
Hello, I'm getting the same issue, for `drug_strength` that is looked up in the `cdm` schema instead of the `vocabulary` schema. 

Regarding `cohort_definition` I'm a bit confused. I used the DDLs for CDMv5.4 to create my `cdm` and `vocabulary` schemas, and the WebAPI-based DDL generation for the `results` schema. And with this, `cohort_definition` is in the `cdm` schema but not in the `results` schema. Is that what is expected and should I set `cohortDatabaseSchema='cdm'` or am I missing something. I also saw some posts saying that the table may be duplicated, that there could be overlap/conflict with WebAPI/ATLAS usage... so I'm lost on the current expectations for the cohort tables. Could anyone clarify please?

**Comment by RomainTching** [comment]
Hello! I'm having the same issue for drug_strength, using `DQDv2.3.0`. The scripts seem to still be looking for drug_strength in the `cdm` schema for checks `FIELD_FK_DOMAIN`, `FIELD_FK_CLASS` and `PLAUSIBLE_TEMPORAL_AFTER`.

**Comment by katy-sadowski** [comment]
@RomainTching thanks for reporting this issue!  Looks like we missed updating those 3 SQL queries with the new flexible schema parameter.  I will ship a fix for this in the next release.
