### ISSUE TITLE
vignettes/AddNewCheck.rmd Add a New Check missing images

### ISSUE THREAD

**Issue by don-torok** [OHDSI/DataQualityDashboard#396]
Images, Figure 1: launchSqlRenderDeveloper and Figure 2: launchSqlRenderDeveloper do not display in the rendered vignette.  The images are in vignettes/images and referenced as ![Figure 1: launchSqlRenderDeveloper](images/library_SQLRender.png)
 and ![Figure 2: launchSqlRenderDeveloper](images/SQLRenderDeveloper.png) in the markdown file AddNewCheck.md.  I did not write the .rmd file.

**Comment by katy-sadowski** [comment]
weird issue! somehow this didn't get fixed after all. right now the website is pulling images from [here](https://github.com/OHDSI/DataQualityDashboard/tree/main/docs/articles/images), where the images have lowercase png but the path in the html file has uppercase PNG. so the images are broken on the website still.  and the .md files in the vignette folder still have lowercase png while the image files in that directory have uppercase PNG. haha.

i'll see if i can go through and make _everything_ lowercase so we can avoid this from causing issues moving forward (it's especially confusing because git diffs and local rendering don't seem to care about case of the suffix).

**Comment by clairblacketer** [comment]
@katy-sadowski if this was fixed on the develop branch that might be why it is still broken. The website runs off of the docs folder on the main branch. It might be worth checking once you merge develop with main to release v2.0.

**Comment by katy-sadowski** [comment]
i merged in the develop branch yesterday (v2 release is up!) and then verified this thinking i could close it. but unfortunately it's broken, probably because there's a mismatch in case between the html and the image in the docs/articles directory.

**Comment by katy-sadowski** [comment]
This is resolved in the v2.1 release.
