### ISSUE TITLE
Error in OMOP_CDMv5.4_Field_Level.csv about offset field check

### ISSUE THREAD

**Issue by mbucalo** [OHDSI/DataQualityDashboard#408]
As indicated in the title I found that in the OMOP_CDMv5.4_Field_Level.csv at line 316 the field offset is surrounded by multiple double quotes that leads the DQD to use it in the query with all capital letters. Removing the quotes allow the DQD to check correctly the NOTE_NLP table

**Comment by katy-sadowski** [comment]
oooh this is fascinating.  i think the field name has quotes since `offset` is a reserved word in SQL.  but when you surround a column name in quotes (in Postgres at least), it makes the column name case sensitive.  however because DQD makes column names [all uppercase](https://github.com/OHDSI/DataQualityDashboard/blob/6c9c8fedb5a545dda6c34112acef40decda1fc5e/R/executeDqChecks.R#L234), it's looking for the "OFFSET" column, which doesn't exist.

it actually looks like this was [already reported](https://github.com/OHDSI/DataQualityDashboard/issues/245) and fixed, by just skipping this field from evaluation by DQD: https://github.com/OHDSI/DataQualityDashboard/blob/6c9c8fedb5a545dda6c34112acef40decda1fc5e/R/executeDqChecks.R#L206.  but the v5.4 thresholds file still has quotes around "offset" so the quoted "offset" isn't getting skipped by this line.  

i think the solution will either be to remove these quotes in the 5.4 thresholds file _or_ revisit the decision to make all column names uppercase (which was done [here](https://github.com/OHDSI/DataQualityDashboard/pull/101), seemingly in response to the same issue, but for Oracle, so not sure there's a universal fix possible...).  i will check with the team on this and get back to you with a fix!

**Comment by katy-sadowski** [comment]
FYI - I chatted with the team and they've already tried to tackle this from multiple angles. The best solution until that column is renamed in CDM will be to skip it from evaluation in the DQD. I'll include the fix to remove the quotes from 5.4 threshold file in our upcoming release.

Thanks for reporting :)

**Comment by mbucalo** [comment]
Thanks to you Katy for the update.

--
Mauro Bucalo
CTO & Product Manager | Biomeris S.r.l
T. +39 0382985055 | M. +39 3284362881

Il 20 dic 2022, 23:43 +0100, Katy Sadowski ***@***.***>, ha scritto:

**Comment by katy-sadowski** [comment]
This is now resolved in the v2.1 release!
