### ISSUE TITLE
Error in executeDqChecks when CDM_SOURCE contains multiple records

### ISSUE THREAD

**Issue by Freia3** [OHDSI/DataQualityDashboard#410]
When executing executeDqChecks, I get the following error message:

Error in if (file == "") file <- stdout() else if (startsWith(file, "|")) { : 
  the condition has length > 1

I don't get the error when there is only one record in the cdm_source table.

The issue is realted to this line:
https://github.com/OHDSI/DataQualityDashboard/blob/main/R/executeDqChecks.R#L291
outputFile <- sprintf("%s-%s.json", tolower(metadata$CDM_SOURCE_ABBREVIATION), endTimestamp)
As I have multiple cdm_source records, I have multiple CDM_SOURCE_ABBREVIATIONs. So he wants to write to multiple files which is not possible.

**Comment by katy-sadowski** [comment]
Hi there!  So technically the CDM_SOURCE table is only supposed to have 1 row in it.  The DQD uses this single row to display/store metadata about the CDM it's been run on.  We can add a check at the start of the executeDqChecks run which gives a more useful error message on this. 

Could you describe a bit your use case for storing multiple rows in the CDM_SOURCE table?   This will help me decide on the best solution for you :)

**Comment by katy-sadowski** [comment]
Hi there @Freia3 , do you still require assistance on this issue?

**Comment by Freia3** [comment]
Hi,
We store multiple data sources in our CDM, that's why we have multiple records. Storing multiple data sources in one CDM is allowed: https://forums.ohdsi.org/t/anyone-storing-multiple-data-sources-in-one-cdm/1849

Would be nice to have at least a more useful error message on this.

Thanks!

**Comment by katy-sadowski** [comment]
Thanks @Freia3 .  Agree a more useful error message is warranted here.  I think we can add a stop condition to this section if there's more than 1 metadata row: https://github.com/OHDSI/DataQualityDashboard/blob/b0957c8dc3327ffe2e070d948dd12d3037d17e47/R/executeDqChecks.R#L111

I am curious if/how you ended up working around the error.  Did you remove rows from cdm_source, or modify the DQD code a bit?  Or is this blocking you from using DQD?

What we really need are standard conventions for populating CDM_SOURCE in the case where multiple sources are stored in the CDM. Then DQD could adapt its use of this table accordingly. Maybe something to bring for discussion with the CDM workgroup, or re-raise on the Forums (it's been a while since that thread you shared!)

**Comment by katy-sadowski** [comment]
This has been fixed in v2.5. DQD will no longer error if CDM_SOURCE contains multiple rows.
