### ISSUE TITLE
strange units in concept level CSV

### ISSUE THREAD

**Issue by vojtechhuser** [OHDSI/DataQualityDashboard#43]
Defining plausible values in inches for A1c is incorrect.

What is the rationale here?

![image](https://user-images.githubusercontent.com/7526119/64549273-5de00780-d2fe-11e9-8560-1564d2386df3.png)

**Comment by clairblacketer** [comment]
@vojtechhuser I agree that is incorrect. I believe what was done here was a grab of all HbA1c records and all units associated (correct or not) and then a biologically plausible range was set up. I think the measurement/unit pairs definitely need some cleaning up because we need to flag implausible values but also implausible units

**Comment by clairblacketer** [comment]
@fdefalco still an issue
