### ISSUE TITLE
plausibleGenderUseDescendants not checking ancestor and all domains of descendants

### ISSUE THREAD

**Issue by lore-edencehealth** [OHDSI/DataQualityDashboard#556]
the plausible gender use descendants check does not seem to check the ancestor itself. 
suggested update:
JOIN @vocabDatabaseSchema.concept_ancestor ca
				ON ca.descendant_concept_id = cdmTable.@cdmFieldName **OR ca.ancestor_concept_id =*cdmTable.@cdmFieldName**

OMOP_CDMv5.4_Concept_Level.csv has checks on condition_occurrence but some of them or its descendants are observations.
OMOP_CDMv5.4_Concept_Level.csv has checks on procedure_occurrence but some of the descendants are observations or measurements. 
Should a copy of the rows be made for these extra cdmTables?

**Comment by katy-sadowski** [comment]
Every concept is its own descendant, so we do not need to add this additional SQL logic. (see https://ohdsi.github.io/TheBookOfOhdsi/StandardizedVocabularies.html#conceptAncestor)

Regarding cross-domain checks, I think this is out of scope for this check.  We'd probably want to add specific checks on gender-specific observations and measurements in order to capture these additional concepts.  I'm actually surprised that the hierarchy contains a mix of domains - @dimshitc is this expected?

**Comment by lore-edencehealth** [comment]
Ok thank you. I should have done a more general check on this but I seem to have used the 1 concept where this does not apply: ancestor_concept_id = 4443343 does not have a descendant with the same concept_id

**Comment by katy-sadowski** [comment]
I filed an issue for additional domain checking here: https://github.com/OHDSI/DataQualityDashboard/issues/564
