### ISSUE TITLE
Missing `pull()` in CodeToRun exclude checks workflow

### ISSUE THREAD

**Issue by katy-sadowski** [OHDSI/DataQualityDashboard#568]
https://github.com/OHDSI/DataQualityDashboard/blob/98c825a9449a5d15413669a7e931f98b1e1c51c9/extras/codeToRun.R#L95

Also, we should call library(dplyr) at the top.

Also, this shouldn't have cdmSourceName in it: https://github.com/OHDSI/DataQualityDashboard/blob/98c825a9449a5d15413669a7e931f98b1e1c51c9/extras/codeToRun.R#L121

**Comment by samhillman** [comment]
Pull request available to https://github.com/OHDSI/DataQualityDashboard/pull/574. Update the checksToExclude by changing the select() to a pull() to make sure we return the vector only rather than a column. Add explicit namespacing and call the library(dplyr) at the top of the commented code. Update the inspect logs code to correct the file.path() argument to include the cdmSourceName only in the .txt file name.
