### ISSUE TITLE
Check: field_fkdomain_episode_episode_object_concept_id doesn't align with OMOP CDM 5.4 Specification

### ISSUE THREAD

**Issue by teenwyman** [OHDSI/DataQualityDashboard#578]
Referring to [OMOP CDM 5.4 Specification](https://ohdsi.github.io/CommonDataModel/cdm54.html#episode):
![image](https://github.com/user-attachments/assets/b18df11b-1d52-4b7b-98eb-dde5b0fbdd43)

•	‘Procedure’ or ‘Regimen’ concepts are applicable for Treatment Regimen Episodes.
•	‘Condition’ concepts are applicable for Disease Episodes.

However, the DQD field_fkdomain_episode_episode_object_concept_id check does not align with it. 
(The number and percent of records that have a value in the EPISODE_OBJECT_CONCEPT_ID field in the EPISODE table that do not conform to the PROCEDURE OR REGIMEN domain)

Also, there is typo misstake in the SQL: co.domain_id NOT IN **(‘Procedure OR Regimen’)**

**Comment by katy-sadowski** [comment]
Sorry about this!  This is a bug that was fixed a while back but somehow reappeared. This check should be disabled for this field because DQD currently does not support checking of multiple domains in this way. I will open a PR to disable this check by default.

In the meantime, you can disable the check in your local threshold file to silence the failure.

**Comment by katy-sadowski** [comment]
This was fixed in release 2.6.2 :)
