### ISSUE TITLE
lab min values should be consistent for same lab test and units

### ISSUE THREAD

**Issue by vojtechhuser** [OHDSI/DataQualityDashboard#69]
for microgram and miligram, I would expect 0.003 and 3 in minimal thresholds

current KB
![image](https://user-images.githubusercontent.com/7526119/68997766-ed161800-0877-11ea-9a51-6e5c7e655113.png)

Even better, encourage single unit per lab test (new type of DQ effort towards single unit when it is easily convertible at ELT time).

**Comment by SSMK-wq** [comment]
Hi,

Yes. I encountered similar issue for lab measurement of 3027114 and unit concept id 8753 (mmol/L).

The actual values are in the range 1-26 but the threshold value in DQD is 69. 

The same measurement in mmol/L when converted to mg/dL, I see few records violating the threshold limit.

I believe there is a mismatch between threshold values for mmol/L and mg/dL for 3027114 which is same as @vojtechhuser's issue. Hence thought of adding it here instead of opening a new issue.

**Comment by clairblacketer** [comment]
I am closing this as we implemented new measurement checks looking for plausible units and we removed the plausible value checks.
