### ISSUE TITLE
Use table aliases instead of fully qualified table names

### ISSUE THREAD

**Issue by clairblacketer** [OHDSI/DataQualityDashboard#79]
In the templated SQL, the joins use fully qualified table names instead of aliases. Let's switch these to alias names

**Comment by CartWill** [comment]
A large number of the queries fail when trying to run against Google BigQuery.  BQ seems to think some of the schema table references are trying to refer to columns.   For Example a rendered query output example appears as this:

`select num_violated_rows, case when denominator.num_rows = 0 then 0 else 1.0*num_violated_rows/denominator.num_rows end  as pct_violated_rows
from
(
	select COUNT(violated_rows.violating_field) as num_violated_rows
	from
	(
		select 'PERSON.person_id' as violating_field, person.* 
		from uchealth_omop.person
		where uchealth_omop.person.person_id is null
	) violated_rows
) violated_row_count,
( 
	select COUNT(*) as num_rows
	from uchealth_omop.person
) denominator
;`

BigQuery seems to think in where clause that the "uchealth_omop.person" part is trying to refer to a column rather than a schema and table.  Adding aliases seems to bypass any issues where trying to refer to a schema and table.

The above query changed to aliases can actually run:

`select num_violated_rows, case when denominator.num_rows = 0 then 0 else 1.0*num_violated_rows/denominator.num_rows end  as pct_violated_rows
from
(
	select COUNT(violated_rows.violating_field) as num_violated_rows
	from
	(
		select 'PERSON.person_id' as violating_field, p.* 
		from uchealth_omop.person p
		where p.person_id is null
	) violated_rows
) violated_row_count,
( 
	select COUNT(*) as num_rows
	from uchealth_omop.person p
) denominator
;`

We'd encourage aliasing everywhere in the source SQL and not just joins.

**Comment by clairblacketer** [comment]
Thank you - there is actually a PR in review to do this to make the code more compatible with big query and it will be available soon

**Comment by alondhe** [comment]
@CartWill -- I have rewritten the query templates to use aliases in the "develop" branch of my fork. 

`devtools::install_github("alondhe/DataQualityDashboard", ref = "develop")`

**Comment by alondhe** [comment]
Fixed in latest commit
